# Generated by Django 4.2.1 on 2023-05-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="username",
        ),
        migrations.AlterField(
            model_name="message",
            name="creator",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="message",
            name="room",
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name="ChatUser",
        ),
        migrations.DeleteModel(
            name="Room",
        ),
    ]
